const TYPE_POST_SUCCESS = 'TYPE_POST_SUCCESS'
const TYPE_POST_ERROR = 'TYPE_POST_ERROR'
const TYPE_POST = 'TYPE_POST'
const CHANGE_TYPE = 'CHANGE_TYPE'
const ADD_TYPE = 'ADD_TYPE'
const ADD_TYPE_SUCCESSS = 'ADD_TYPE_SUCCESSS'
const ADD_TYPE_ERROR = 'ADD_TYPE_ERROR'
/*editer*/
const EDITER_TITLE = 'EDITER_TITLE'
const EDITER_CONTENT = 'EDITER_CONTENT'

/*login*/
const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
const LOGIN_ERROR = 'LOGIN_ERROR'
const LOGIN = 'LOGIN'

export {
    TYPE_POST_SUCCESS,
    TYPE_POST_ERROR,
    TYPE_POST,
    CHANGE_TYPE,
    ADD_TYPE,
    ADD_TYPE_SUCCESSS,
    ADD_TYPE_ERROR,
    EDITER_CONTENT,
    EDITER_TITLE,
    LOGIN,
    LOGIN_SUCCESS,
    LOGIN_ERROR
}